name: Use token
on: [push]
jobs:
  use_token:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Use token
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          node index.js